"use client";

import {useMemo,useState} from "react";
type Lang="en"|"ru"|"uz";

const lessons=[
 {unit:"BOOK 01",ar:"العربية بين يديك",en:"Arabic Between Your Hands — Book 1",ru:"Арабский перед тобой — Книга 1",uz:"Arab tili qo‘lingizda — 1-kitob",file:"/arabic/1st-Book.pptx",slides:3,tone:"mint"},
 {unit:"UNIT 09",ar:"الوحدة التاسعة",en:"Unit 9",ru:"Урок 9",uz:"9-bo‘lim",file:"/arabic/U09.pptx",slides:52,tone:"coral"},
 {unit:"UNIT 10",ar:"الوحدة العاشرة",en:"Unit 10",ru:"Урок 10",uz:"10-bo‘lim",file:"/arabic/U10.pptx",slides:58,tone:"gold"},
 {unit:"UNIT 11",ar:"الوحدة الحادية عشرة",en:"Unit 11",ru:"Урок 11",uz:"11-bo‘lim",file:"/arabic/U11.pptx",slides:51,tone:"blue"}
];
const copy={
 en:{library:"Arabic Library",numbers:"Numbers",eyebrow:"Your Arabic course, all in one place",title:"Learn from the original lessons.",sub:"Open or download the available course presentations and continue learning at your own pace.",search:"Search lessons…",files:"course files",slides:"slides",open:"Open lesson",download:"Download",quizTitle:"Read the Arabic number",quizSub:"Choose the matching value",score:"Score",streak:"Streak",best:"Best",next:"Next number",correct:"Perfect!",incorrect:"Not quite — the answer is",reset:"Reset session"},
 ru:{library:"Библиотека",numbers:"Числа",eyebrow:"Весь курс арабского в одном месте",title:"Учитесь по оригинальным урокам.",sub:"Открывайте или скачивайте доступные презентации курса и занимайтесь в своём темпе.",search:"Поиск уроков…",files:"файла курса",slides:"слайдов",open:"Открыть урок",download:"Скачать",quizTitle:"Прочитайте арабское число",quizSub:"Выберите правильное значение",score:"Счёт",streak:"Серия",best:"Рекорд",next:"Следующее число",correct:"Верно!",incorrect:"Правильный ответ:",reset:"Начать заново"},
 uz:{library:"Arab tili kutubxonasi",numbers:"Raqamlar",eyebrow:"Arab tili kursingiz bir joyda",title:"Asl darslardan o‘rganing.",sub:"Mavjud kurs taqdimotlarini oching yoki yuklab oling va o‘z tezligingizda o‘rganing.",search:"Darslarni qidiring…",files:"ta kurs fayli",slides:"slayd",open:"Darsni ochish",download:"Yuklab olish",quizTitle:"Arabcha raqamni o‘qing",quizSub:"Mos qiymatni tanlang",score:"Ball",streak:"Seriya",best:"Rekord",next:"Keyingi raqam",correct:"Ajoyib!",incorrect:"To‘g‘ri javob:",reset:"Qayta boshlash"}
};
const arabic=(n:number)=>String(n).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[Number(d)]);
const makeQ=(last=-1)=>{let value=Math.floor(Math.random()*999)+1;while(value===last)value=Math.floor(Math.random()*999)+1;const s=new Set([value]);while(s.size<4){const x=Math.max(0,Math.min(999,value+Math.floor(Math.random()*41)-20));if(x!==value)s.add(x)}return{value,choices:[...s].sort(()=>Math.random()-.5)}};

export default function Home(){
 const[lang,setLang]=useState<Lang>("en"),[view,setView]=useState<"library"|"numbers">("library"),[query,setQuery]=useState("");
 const[question,setQuestion]=useState(()=>makeQ()),[choice,setChoice]=useState<number|null>(null),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0);const t=copy[lang];
 const filtered=useMemo(()=>lessons.filter(x=>`${x.ar} ${x.en} ${x.ru} ${x.uz} ${x.unit}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const answer=(n:number)=>{if(choice!==null)return;setChoice(n);if(n===question.value){setScore(s=>s+1);setStreak(s=>{const x=s+1;setBest(b=>Math.max(b,x));return x})}else setStreak(0)};
 const next=()=>{setQuestion(makeQ(question.value));setChoice(null)};
 return <main><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView("library")}}><span className="brandmark">ن</span><span>Natiq</span></a><nav><button className={view==="library"?"active":""} onClick={()=>setView("library")}>{t.library}</button><button className={view==="numbers"?"active":""} onClick={()=>setView("numbers")}>{t.numbers}</button></nav><div className="langs">{(["en","ru","uz"] as Lang[]).map(l=><button key={l} className={lang===l?"active":""} onClick={()=>setLang(l)}>{l.toUpperCase()}</button>)}</div></header>
 {view==="library"?<><section className="hero library-hero"><div><p className="eyebrow"><span>✦</span>{t.eyebrow}</p><h1>{t.title}</h1><p>{t.sub}</p></div><div className="hero-ar"><span>اِقْرَأْ</span><small>iqra’ · read</small></div></section><section className="workspace"><div className="toolbar"><div><p className="section-kicker">{t.library}</p><h2>{lessons.length} {t.files}</h2></div><div className="actions"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></label></div></div><div className="lesson-grid">{filtered.map((lesson,i)=><article className={`lesson-card ${lesson.tone}`} key={lesson.file}><div className="lesson-cover"><span className="lesson-no">{String(i+1).padStart(2,"0")}</span><span className="lesson-ar" dir="rtl">{lesson.ar}</span><div className="lesson-lines"><i/><i/><i/></div></div><div className="lesson-body"><span className="unit">{lesson.unit}</span><h3>{lesson[lang]}</h3><p>{lesson.slides} {t.slides} · PowerPoint</p><div className="lesson-actions"><a className="primary open-file" href={lesson.file} target="_blank" rel="noreferrer">{t.open} ↗</a><a className="soft download-file" href={lesson.file} download>↓ {t.download}</a></div></div></article>)}</div></section></>:<section className="quiz-wrap"><div className="quiz-intro"><p className="eyebrow"><span>✦</span>{t.numbers}</p><h1>{t.quizTitle}</h1><p>{t.quizSub}</p></div><div className="stats"><div><span>{t.score}</span><strong>{score}</strong></div><div><span>{t.streak}</span><strong>{streak}</strong></div><div><span>{t.best}</span><strong>{best}</strong></div></div><div className="quiz-card"><div className="number" dir="rtl">{arabic(question.value)}</div><div className="answers">{question.choices.map(n=><button key={n} disabled={choice!==null} onClick={()=>answer(n)} className={choice!==null?(n===question.value?"correct":n===choice?"wrong":"muted"):""}>{n}</button>)}</div>{choice!==null&&<div className={`feedback ${choice===question.value?"good":"bad"}`}><span>{choice===question.value?"✓":"×"}</span><strong>{choice===question.value?t.correct:`${t.incorrect} ${question.value}`}</strong><button onClick={next}>{t.next} →</button></div>}</div><button className="reset" onClick={()=>{setScore(0);setStreak(0);next()}}>↻ {t.reset}</button></section>}
 <footer><span>نَاطِق · Natiq</span><span>Arabic made connected.</span></footer></main>
}
