"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Lang="en"|"ru"|"uz";
type Word={ar:string,en:string,ru:string,uz:string,exampleAr?:string,exampleEn?:string};
type Unit={number:string,ar:string,en:string,ru:string,uz:string,tone:string,words:Word[]};
const ui={
 en:{vocab:"Vocabulary",numbers:"Numbers",intro:"CONNECTED ARABIC VOCABULARY",title:"Words that lead to more words.",sub:"Explore vocabulary from Units 9–11. Every entry includes translations and a connected Arabic example you can follow word by word.",folders:"Vocabulary folders",words:"words",open:"Explore unit",back:"All units",search:"Search Arabic, English, Russian or Uzbek…",add:"Add word",arabic:"Arabic word",english:"English",russian:"Russian",uzbek:"Uzbek",example:"Example sentence",exampleTranslation:"Example translation",empty:"No matching words",close:"Close",save:"Save word",newWord:"Add vocabulary",hint:"Select an Arabic word to open its full entry.",quiz:"Read the Arabic number",choose:"Choose the matching value",score:"Score",streak:"Streak",best:"Best",next:"Next number",correct:"Perfect!",answer:"The answer is",reset:"Reset session"},
 ru:{vocab:"Словарь",numbers:"Числа",intro:"СВЯЗАННАЯ АРАБСКАЯ ЛЕКСИКА",title:"Слова, ведущие к новым словам.",sub:"Изучайте лексику разделов 9–11. Каждая запись содержит переводы и связанный арабский пример.",folders:"Словарные разделы",words:"слов",open:"Открыть раздел",back:"Все разделы",search:"Поиск на арабском, английском, русском или узбекском…",add:"Добавить слово",arabic:"Арабское слово",english:"Английский",russian:"Русский",uzbek:"Узбекский",example:"Пример",exampleTranslation:"Перевод примера",empty:"Ничего не найдено",close:"Закрыть",save:"Сохранить слово",newWord:"Добавить слово",hint:"Нажмите арабское слово, чтобы открыть полную запись.",quiz:"Прочитайте арабское число",choose:"Выберите правильное значение",score:"Счёт",streak:"Серия",best:"Рекорд",next:"Следующее число",correct:"Верно!",answer:"Правильный ответ:",reset:"Начать заново"},
 uz:{vocab:"Lug‘at",numbers:"Raqamlar",intro:"BOG‘LANGAN ARABCHA LUG‘AT",title:"Yangi so‘zlarga yetaklaydigan so‘zlar.",sub:"9–11-bo‘limlar lug‘atini o‘rganing. Har bir yozuv tarjimalar va bog‘langan arabcha misolni o‘z ichiga oladi.",folders:"Lug‘at bo‘limlari",words:"ta so‘z",open:"Bo‘limni ochish",back:"Barcha bo‘limlar",search:"Arab, ingliz, rus yoki o‘zbek tilida qidiring…",add:"So‘z qo‘shish",arabic:"Arabcha so‘z",english:"Inglizcha",russian:"Ruscha",uzbek:"O‘zbekcha",example:"Misol gap",exampleTranslation:"Misol tarjimasi",empty:"Mos so‘z topilmadi",close:"Yopish",save:"So‘zni saqlash",newWord:"Lug‘at qo‘shish",hint:"To‘liq yozuvni ochish uchun arabcha so‘zni bosing.",quiz:"Arabcha raqamni o‘qing",choose:"Mos qiymatni tanlang",score:"Ball",streak:"Seriya",best:"Rekord",next:"Keyingi raqam",correct:"Ajoyib!",answer:"To‘g‘ri javob:",reset:"Qayta boshlash"}
};
const arabicNumber=(n:number)=>String(n).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[Number(d)]);
const ones=["صفر","واحد","اثنان","ثلاثة","أربعة","خمسة","ستة","سبعة","ثمانية","تسعة","عشرة","أحد عشر","اثنا عشر","ثلاثة عشر","أربعة عشر","خمسة عشر","ستة عشر","سبعة عشر","ثمانية عشر","تسعة عشر"];
const tens=["","","عشرون","ثلاثون","أربعون","خمسون","ستون","سبعون","ثمانون","تسعون"];
const hundreds=["","مائة","مائتان","ثلاثمائة","أربعمائة","خمسمائة","ستمائة","سبعمائة","ثمانمائة","تسعمائة"];
function arabicWords(n:number){if(n<20)return ones[n];if(n<100){const o=n%10,t=Math.floor(n/10);return o?`${ones[o]} و${tens[t]}`:tens[t]}const h=Math.floor(n/100),r=n%100;return r?`${hundreds[h]} و${arabicWords(r)}`:hundreds[h]}
const makeQ=(last=-1)=>{let value=Math.floor(Math.random()*999)+1;while(value===last)value=Math.floor(Math.random()*999)+1;const s=new Set([value]);while(s.size<4){const x=Math.max(0,Math.min(999,value+Math.floor(Math.random()*41)-20));if(x!==value)s.add(x)}return{value,choices:[...s].sort(()=>Math.random()-.5)}};
function linksFor(word:Word,unit:Unit){const anchor=unit.number==="09"?unit.words.find(x=>x.ar.includes("هُنَا")):unit.number==="10"?unit.words.find(x=>x.ar.includes("الْجَوُّ")):unit.words.find(x=>x.ar.includes("هُنَاكَ"));return anchor&&anchor.ar!==word.ar?[anchor,word]:[word]}
const patterns={
 "09":[["أَشْتَرِي {w} مِنَ السُّوقِ.","I buy {e} from the market."],["أَبْحَثُ عَنْ {w} فِي الْمَتْجَرِ.","I look for {e} in the shop."],["وَجَدْتُ {w} فِي هٰذَا الْقِسْمِ.","I found {e} in this department."],["أَحْتَاجُ إِلَى {w} الْيَوْمَ.","I need {e} today."],["يَعْرِضُ الْبَائِعُ {w} لِلْمُشْتَرِي.","The seller shows {e} to the customer."],["هَلْ عِنْدَكُمْ {w}؟","Do you have {e}?"],["اخْتَرْتُ {w} بَعْدَ أَنْ نَظَرْتُ إِلَيْهِ.","I chose {e} after looking at it."],["سَأَلْتُ الْبَائِعَ عَنْ {w}.","I asked the seller about {e}."]],
 "10":[["نَتَحَدَّثُ عَنْ {w} فِي دَرْسِ الْجَوِّ.","We talk about {e} in the weather lesson."],["أَرَى {w} عِنْدَمَا أَنْظُرُ مِنَ النَّافِذَةِ.","I see {e} when I look through the window."],["سَأَلَ الْمُعَلِّمُ الطُّلَّابَ عَنْ {w}.","The teacher asked the students about {e}."],["نَسْمَعُ كَثِيرًا عَنْ {w} فِي النَّشْرَةِ.","We often hear about {e} in the forecast."],["يَتَغَيَّرُ {w} مَعَ فُصُولِ السَّنَةِ.","{e} changes with the seasons."],["كَتَبْتُ جُمْلَةً جَدِيدَةً عَنْ {w}.","I wrote a new sentence about {e}."],["نُشَاهِدُ {w} فِي هٰذَا الْمَكَانِ.","We observe {e} in this place."],["تَعَلَّمْتُ مَعْنَى {w} فِي الدَّرْسِ.","I learned the meaning of {e} in the lesson."]],
 "11":[["تَحَدَّثْنَا عَنْ {w} فِي دَرْسِ النَّاسِ وَالْأَمَاكِنِ.","We talked about {e} in the people and places lesson."],["رَأَيْتُ {w} فِي الرِّحْلَةِ.","I saw {e} on the trip."],["سَأَلَ الصَّدِيقُ عَنْ {w}.","The friend asked about {e}."],["قَرَأْتُ خَبَرًا عَنْ {w} الْيَوْمَ.","I read a story about {e} today."],["يَعْرِفُ الطَّالِبُ مَعْنَى {w}.","The student knows the meaning of {e}."],["ذَكَرَ الْمُعَلِّمُ {w} فِي الْفَصْلِ.","The teacher mentioned {e} in class."],["كَتَبْتُ {w} فِي دَفْتَرِي.","I wrote {e} in my notebook."],["يَرْتَبِطُ {w} بِحَيَاةِ النَّاسِ.","{e} is connected to people’s lives."]]
} as const;
function exampleFor(word:Word,unit:Unit){if(word.exampleAr)return{ar:word.exampleAr,en:word.exampleEn||""};const index=Math.max(0,unit.words.findIndex(x=>x.ar===word.ar)),set=patterns[unit.number as keyof typeof patterns]||patterns["11"],[ar,en]=set[index%set.length];return{ar:ar.replace("{w}",word.ar),en:en.replace("{e}",word.en)}}
const norm=(s:string)=>s.replace(/[ًٌٍَُِّْـ.,؟]/g,"");
function LinkedSentence({sentence,unit,openWord}:{sentence:string,unit:Unit,openWord:(w:Word)=>void}){return <>{sentence.split(/(\s+)/).map((part,i)=>{const found=unit.words.find(x=>norm(x.ar)===norm(part));return found?<button key={i} onClick={()=>openWord(found)}>{part}</button>:<span key={i}>{part}</span>})}</>}

export default function VocabApp({units:source}:{units:Unit[]}){
 const[lang,setLang]=useState<Lang>("en"),[view,setView]=useState<"vocab"|"numbers">("vocab"),[active,setActive]=useState<number|null>(null),[selected,setSelected]=useState<Word|null>(null),[query,setQuery]=useState(""),[adding,setAdding]=useState(false),[custom,setCustom]=useState<Record<string,Word[]>>({});
 const[q,setQ]=useState(()=>makeQ()),[choice,setChoice]=useState<number|null>(null),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0);const t=ui[lang];
 useEffect(()=>{try{setCustom(JSON.parse(localStorage.getItem("natiq-custom-words")||"{}"))}catch{}},[]);
 const unit=active===null?null:source[active];const allWords=useMemo(()=>unit?[...unit.words,...(custom[unit.number]||[])]:[],[unit,custom]);const filtered=useMemo(()=>allWords.filter(x=>`${x.ar} ${x.en} ${x.ru} ${x.uz}`.toLowerCase().includes(query.trim().toLowerCase())),[allWords,query]);
 const openWord=(word:Word)=>{setSelected(word);window.scrollTo({top:0,behavior:"smooth"})};
 const addWord=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!unit)return;const f=new FormData(e.currentTarget),word:Word={ar:String(f.get("ar")),en:String(f.get("en")),ru:String(f.get("ru")),uz:String(f.get("uz")),exampleAr:String(f.get("exampleAr")),exampleEn:String(f.get("exampleEn"))};const next={...custom,[unit.number]:[...(custom[unit.number]||[]),word]};setCustom(next);localStorage.setItem("natiq-custom-words",JSON.stringify(next));setAdding(false);setSelected(word)};
 const answer=(n:number)=>{if(choice!==null)return;setChoice(n);if(n===q.value){setScore(s=>s+1);setStreak(s=>{const x=s+1;setBest(b=>Math.max(b,x));return x})}else setStreak(0)};const next=()=>{setQ(makeQ(q.value));setChoice(null)};
 const goHome=()=>{setView("vocab");setActive(null);setSelected(null);setQuery("")};
 return <main><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();goHome()}}><span className="brandmark">ن</span><span>Natiq</span></a><nav><button className={view==="vocab"?"active":""} onClick={goHome}>{t.vocab}</button><button className={view==="numbers"?"active":""} onClick={()=>setView("numbers")}>{t.numbers}</button></nav><div className="langs">{(["en","ru","uz"] as Lang[]).map(l=><button key={l} className={lang===l?"active":""} onClick={()=>setLang(l)}>{l.toUpperCase()}</button>)}</div></header>
 {view==="vocab"&&active===null&&<><section className="hero connected-hero"><div><p className="eyebrow"><span>✦</span>{t.intro}</p><h1>{t.title}</h1><p>{t.sub}</p></div><div className="connection-art"><span>كَلِمَة</span><i/><b>مَعْنًى</b><i/><em>جُمْلَة</em></div></section><section className="workspace"><div className="toolbar"><div><p className="section-kicker">NATIQ LIBRARY</p><h2>{t.folders}</h2></div></div><div className="folder-grid">{source.map((u,i)=><button className={`folder-card ${u.tone}`} key={u.number} onClick={()=>setActive(i)}><span className="folder-tab"/><span className="folder-number">UNIT {u.number}</span><span className="folder-ar" dir="rtl">{u.ar}</span><strong>{u[lang]}</strong><span className="folder-meta">{u.words.length+(custom[u.number]?.length||0)} {t.words}</span><span className="folder-open">{t.open} <b>→</b></span></button>)}</div></section></>}
 {view==="vocab"&&unit&&<section className="table-page"><div className="table-nav"><button className="back" onClick={()=>{setActive(null);setSelected(null);setQuery("")}}>← {t.back}</button><button className="primary" onClick={()=>setAdding(true)}>＋ {t.add}</button></div><div className={`unit-banner ${unit.tone}`}><div><span>UNIT {unit.number}</span><h1 dir="rtl">{unit.ar}</h1><p>{unit[lang]} · {allWords.length} {t.words}</p></div><span className="unit-mark">{arabicNumber(Number(unit.number))}</span></div>
 {selected&&<WordDetail word={selected} unit={unit} lang={lang} close={()=>setSelected(null)} openWord={openWord}/>}<label className="vocab-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></label><p className="table-hint">↗ {t.hint}</p><div className="vocab-table-wrap"><table className="vocab-table"><thead><tr><th>{t.arabic}</th><th>{t.english}</th><th>{t.russian}</th><th>{t.uzbek}</th><th>{t.example}</th><th>{t.exampleTranslation}</th></tr></thead><tbody>{filtered.map((word,i)=>{const ex=exampleFor(word,unit);return <tr key={`${word.ar}-${i}`}><td><button className="arabic-entry" dir="rtl" onClick={()=>openWord(word)}>{word.ar}</button></td><td>{word.en}</td><td>{word.ru}</td><td>{word.uz}</td><td className="example-ar" dir="rtl"><span className="example-label">{t.example}</span><LinkedSentence sentence={ex.ar} unit={unit} openWord={openWord}/></td><td className="example-translation"><span className="example-label">{t.exampleTranslation}</span>{ex.en}</td></tr>})}</tbody></table>{filtered.length===0&&<p className="vocab-empty">{t.empty}</p>}</div></section>}
 {view==="numbers"&&<section className="quiz-wrap"><div className="quiz-intro"><p className="eyebrow"><span>✦</span>{t.numbers}</p><h1>{t.quiz}</h1><p>{t.choose}</p></div><div className="stats"><div><span>{t.score}</span><strong>{score}</strong></div><div><span>{t.streak}</span><strong>{streak}</strong></div><div><span>{t.best}</span><strong>{best}</strong></div></div><div className="quiz-card"><div className="number" dir="rtl">{arabicNumber(q.value)}</div><div className="answers arabic-answers word-answers">{q.choices.map(n=><button key={n} dir="rtl" disabled={choice!==null} onClick={()=>answer(n)} className={choice!==null?(n===q.value?"correct":n===choice?"wrong":"muted"):""}>{arabicWords(n)}</button>)}</div>{choice!==null&&<div className={`feedback ${choice===q.value?"good":"bad"}`}><strong>{choice===q.value?t.correct:`${t.answer} ${arabicWords(q.value)}`}</strong><button onClick={next}>{t.next} →</button></div>}</div><button className="reset" onClick={()=>{setScore(0);setStreak(0);next()}}>↻ {t.reset}</button></section>}
 {adding&&unit&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setAdding(false)}}><form className="modal add-modal" onSubmit={addWord}><div className="modal-head"><div><p className="mini">UNIT {unit.number}</p><h2>{t.newWord}</h2></div><button type="button" onClick={()=>setAdding(false)}>×</button></div><label>{t.arabic}<input name="ar" dir="rtl" required/></label><div className="form-row"><label>{t.english}<input name="en" required/></label><label>{t.russian}<input name="ru" required/></label><label>{t.uzbek}<input name="uz" required/></label></div><label>{t.example}<input name="exampleAr" dir="rtl" required/></label><label>{t.exampleTranslation}<input name="exampleEn" required/></label><div className="form-actions"><button type="button" className="soft" onClick={()=>setAdding(false)}>{t.close}</button><button className="primary">{t.save}</button></div></form></div>}<footer><span>نَاطِق · Natiq</span><span>Arabic made connected.</span></footer></main>}

function WordDetail({word,unit,lang,close,openWord}:{word:Word,unit:Unit,lang:Lang,close:()=>void,openWord:(w:Word)=>void}){const ex=exampleFor(word,unit),t=ui[lang];return <article className="selected-entry"><div className="selected-title"><span>SELECTED VOCABULARY ENTRY</span><button onClick={close}>× {t.close}</button></div><div className="selected-table-wrap"><table className="selected-table"><thead><tr><th>{t.arabic}</th><th>{t.english}</th><th>{t.russian}</th><th>{t.uzbek}</th><th>{t.example}</th><th>{t.exampleTranslation}</th></tr></thead><tbody><tr><td><strong dir="rtl">{word.ar}</strong></td><td>{word.en}</td><td>{word.ru}</td><td>{word.uz}</td><td className="example-ar" dir="rtl"><LinkedSentence sentence={ex.ar} unit={unit} openWord={openWord}/></td><td>{ex.en}</td></tr></tbody></table></div></article>}
